name: polygon_painter
description: "A flutter package to draw equilateral polygons on a canvas."
version: 1.0.0
repository: https://github.com/melihhakanpektas/polygon_painter
homepage:

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
